name: haylau_spider_solitaire
description: "Spider Solitaire (Haylau)"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/spider_watermark.png
