// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by: tool/generate_solvable_seeds_1suit.dart

const List<int> dailySolvableSeeds1Suit = <int>[

];

const List<int> randomSolvableSeeds1Suit = <int>[

];
