// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by: tool/generate_solvable_seeds_4suit.dart

import 'solvable_solution_step.dart';

const Map<int, List<SolutionStepDto>> solutionFirst30_4Suit = <int, List<SolutionStepDto>>{};

const Map<int, List<SolutionStepDto>> solutionFull_4Suit = <int, List<SolutionStepDto>>{};
