// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by: tool/generate_solvable_seeds_2suit.dart

const List<int> dailySolvableSeeds2Suit = <int>[
  1,
  2,
];

const List<int> randomSolvableSeeds2Suit = <int>[
  3,
  4,
  9,
];
